config/routes.rb
TechnicalChallenge::Application.routes.draw do

  root 'claims#index'

  resources :claims do
    resources :emails, :notes
  end

end

app/models/claim.rb
class Claim
  include Mongoid::Document
  include Mongoid::Timestamps

  field :status, type: String, default: 'open'
  field :claim_id, type: String
  field :claimant_name, type: String
  field :postcode, type: String
  field :policy_no, type: String
  field :settlement_amount, type: String
  field :settlement_date, type: String

  has_many :emails
  has_many :notes

  def self.search(search)
    if search
      any_of({ :claim_id => "#{search}"}, { :claimant_name => "#{search}"})
    end
  end
end

app/models/email.rb
class Email
  include Mongoid::Document
  include Mongoid::Timestamps

  field :subject, type: String
  field :body, type: String
  field :from, type: String
  field :to, type: String

  belongs_to :claim
end

app/models/note.rb
class Note
  include Mongoid::Document
  include Mongoid::Timestamps

  field :body, type: String

  belongs_to :claim
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  before_action :set_claim, only: [:show, :edit, :update, :destroy]

  layout :choose_layout
  # require 'will_paginate/array'

  # GET /claims
  # GET /claims.json
  def index
    if params[:search].blank?
      @claims = Claim.all.order('created_at DESC').page params[:page]
    else
      @claims = Claim.search(params[:search]).page params[:page]
    end
  end

  # GET /claims/1
  # GET /claims/1.json
  def show
  end

  # GET /claims/new
  def new
    @claim = Claim.new
  end

  # GET /claims/1/edit
  def edit
  end

  # POST /claims
  # POST /claims.json
  def create
    @claim = Claim.new(claim_params)

    respond_to do |format|
      if @claim.save
        format.html { redirect_to edit_claim_path(@claim), notice: 'Claim was successfully created.' }
        format.json { render action: 'show', status: :created, location: @claim }
      else
        format.html { render action: 'new' }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /claims/1
  # PATCH/PUT /claims/1.json
  def update
    puts "\n\r in the update action \n\r\n\r"
    puts "\n\r this is the claim", @claim
    puts @claim.status

    respond_to do |format|
      puts @claim.status

      if @claim.update(claim_params)
        # puts "\n\r this is the claim", @claim
        puts @claim.status
        if @claim.status == 'settled'
          @claim.settlement_date = DateTime.now
          puts DateTime.now
          @claim.save
        end

        format.html { redirect_to claims_path, notice: 'Claim was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /claims/1
  # DELETE /claims/1.json
  def destroy
    @claim.destroy
    respond_to do |format|
      format.html { redirect_to claims_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_claim
      @claim = Claim.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def claim_params
      params.require(:claim).permit(:claim_id, :claimant_name, :postcode, :policy_no, :status, :settlement_amount, :settlement_date)
    end

    def choose_layout
      if ["edit", "new"].include?(params[:action])
        'claim_detail'
      else
        'application'
      end
    end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :set_claim_and_email

  layout "claim_detail"

  # GET /emails
  # GET /emails.json
  def index
    @emails = @claim.emails.page(params[:page]).per(50)
  end

  # GET /emails/1
  # GET /emails/1.json
  def show
  end

  # GET /emails/new
  def new
    @email = @claim.emails.new
  end

  # POST /emails
  # POST /emails.json
  def create
    @email = @claim.emails.new(email_params)

    respond_to do |format|
      if @email.save
        format.html { redirect_to @email, notice: 'Email was successfully created.' }
        format.json { render action: 'show', status: :created, location: @email }
      else
        format.html { render action: 'new' }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emails/1
  # DELETE /emails/1.json
  def destroy
    @email.destroy
    respond_to do |format|
      format.html { redirect_to emails_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_claim_and_email
      @claim = Claim.find(params[:claim_id])
      @email = @claim.emails.find(params[:id]) unless params[:id].nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_params
      params.require(:email).permit(:subject, :body, :from, :to)
    end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_claim_and_note

  layout "claim_detail"

  # GET /notes
  # GET /notes.json
  def index

  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = @claim.notes.new
    @notes = @claim.notes.order('created_at DESC')
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = @claim.notes.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @claim, notice: 'Note was successfully created.' }
        format.json { render action: 'show', status: :created, location: @note }
      else
        format.html { render action: 'new' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emails/1
  # DELETE /emails/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to @claim }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_claim_and_note
      @claim = Claim.find(params[:claim_id])
      @note = @claim.notes.find(params[:id]) unless params[:id].nil?
    end

    def note_params
      params.require(:note).permit(:body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/views/claims/_form.html.erb
<%= form_for @claim, :html => { :class => 'form-horizontal', :role => "form" } do |f| %>
  <div class="form-group">
    <%= f.label :status, :class => 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.select :status, options_for_select(["open", "settled", "cancelled"]), :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :claim_id, :class => 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :claim_id, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :claimant_name, :class => 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :claimant_name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :postcode, :class => 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :postcode, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :policy_no, :class => 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :policy_no, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :settlement_amount, :class => 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :settlement_amount, :readonly => f.object.status == "settled", :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :settlement_date, :class => 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :settlement_date, :readonly => f.object.status == "settled", :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.back', :default => t("helpers.links.back")),
                claims_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/claims/edit.html.erb
<%- model_class = Claim -%>
<% content_for :title do %>
	<%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
<% end %>

<%= render :partial => 'form' %>

app/views/claims/index.html.erb
<%- model_class = Claim -%>
<div class="page-header">
  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_claim_path,
            :class => 'btn btn-primary pull-right' %>
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
</div>

<%= form_tag claims_path, method: :get do %>
  <div class="form-group col-md-offset-3 col-sm-12">
    <div class="col-sm-4">
      <%= text_field_tag :search, params[:search], placeholder: "Search...", :class => 'form-control' %>
    </div>
    <div class="col-sm-2">
      <%= button_tag 'Search', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:claim_id) %></th>
      <th><%= model_class.human_attribute_name(:claimant_name) %></th>
      <th><%= model_class.human_attribute_name(:postcode) %></th>
      <th><%= model_class.human_attribute_name(:policy_no) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:settlement_amount) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @claims.each do |claim| %>
      <tr>
        <td><%= link_to claim.claim_id, edit_claim_path(claim), :class => "status #{claim.status}" %></td>
        <td><%= claim.claimant_name %></td>
        <td><%= claim.postcode %></td>
        <td><%= claim.policy_no %></td>
        <td><%=l claim.created_at, format: :claim_time %></td>
        <td><%= claim.settlement_amount %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_claim_path(claim), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      claim_path(claim),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @claims %>

app/views/claims/new.html.erb
<%- model_class = Claim -%>
<% content_for :title do %>
	<%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %>
<% end %>
<%= render :partial => 'form' %>

app/views/claims/show.html.erb
<%- model_class = Claim -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:claim_id) %>:</strong></dt>
  <dd><%= @claim.claim_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:claimant_name) %>:</strong></dt>
  <dd><%= @claim.claimant_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:postcode) %>:</strong></dt>
  <dd><%= @claim.postcode %></dd>
  <dt><strong><%= model_class.human_attribute_name(:policy_no) %>:</strong></dt>
  <dd><%= @claim.policy_no %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              claims_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_claim_path(@claim), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              claim_path(@claim),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TechnicalChallenge" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="container-fluid">

      <!-- Static navbar -->
      <div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle Navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Claimable</a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Claims <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "List", claims_path %></li>
                  <li><%= link_to "New", new_claim_path %></li>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="/">Logout</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </div>

      <!-- Main component for a primary marketing message or call to action -->
      <div class="container">
        <%= content_for?(:content) ? yield(:content) : yield %>
    	</div>

    </div> <!-- /container -->

	<div id="footer">
       <p class="text-muted">Claimable Ltd. &copy; <%= Date.current.year %></p>
    </div>

  </body>
</html>

app/views/layouts/claim_detail.html.erb
<% content_for :content do %>
	<div class="row">
		<% if content_for(:title) %>
			<div class="page-header">
	  		<h2><span class="label label-default"><%= @claim.claim_id %></span><%= yield(:title) %></h2>
	  		<% if @claim.created_at %>
          <span class="label label-default pull-right created_at"><%=l @claim.created_at %></span>
        <% end %>
  		</div>
		<% end %>
		<div class="col-sm-3 col-md-2">
		  <%= render "layouts/shared/sidebar" %>
		</div>
		<div class="col-sm-9 col-md-10">
			<%= yield %>
		</div>
	</div>
<% end %>

<%= render file: "layouts/application" %>

app/views/layouts/shared/_sidebar.html.erb
<ul class="nav nav-pills nav-stacked">
  <% if @claim.persisted? %>
  	<li <%= params[:controller] == "claims" ? "class=active" : nil %>><%= link_to "Edit Claim", edit_claim_path(@claim) %></li>
  	<li <%= params[:controller] == "emails" ? "class=active" : nil %>><%= link_to "Emails", claim_emails_path(@claim) %></li>
  	<li <%= params[:controller] == "notes" ? "class=active" : nil %>><%= link_to "Notes", new_claim_note_path(@claim) %></li>
	<% else %>
		<li class="active"><a href="#">Claim Details</a></li>
  	<li class="disabled"><a href="#">Emails</a></li>
  	<li class="disabled"><a href="#">Notes</a></li>
	<% end %>
</ul>

app/views/notes/_form.html.erb
<%= form_for @note, url: {action: "create"}, :html => { :class => 'form-horizontal', :role => "form" } do |f| %>
  <div class="form-group">
    <%= f.label :body, :class => 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_area :body, cols: 20, rows: 5, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.back', :default => t("helpers.links.back")),
                claims_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/notes/new.html.erb
<%- model_class = Note -%>
<% content_for :title do %>
  <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
<% end %>

<%= render :partial => 'form' %>

<% @notes.each do |note| %>
  <div class="alert alert-primary col-sm-offset-3 col-sm-9" role="alert">
    <h5><%=l note.created_at %></h5>
    <p><%= note.body %></p>
    <div class="col-sm-offset-11">
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  claim_note_path(@claim, note),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger btn-xs' %>
    </div>
  </div>
<% end %>